// view/src/App.vue
<template>
    <MenuBarComponent />
    <main class="bg-slate-100 flex flex-col h-screen">
        <router-view />
    </main>
</template>

<script>
import MenuBarComponent from './components/MenuBarComponent'

export default {
    components: {
        MenuBarComponent,
    },
};
</script>

<style></style>

// client/src/App.tsx
import { Outlet, useRouteError } from 'react-router-dom';

import MenuBar from './components/MenuBar';
import ErrorElement from './components/ErrorElement';

export default function App() {
	const error = useRouteError();

	return (
		<div className="flex flex-col h-screen">
			<MenuBar />
			<main className="flex-1 overflow-auto bg-gradient-to-r from-violet-100 to-pink-100">
				{error ? <ErrorElement /> : <Outlet />}
			</main>
		</div>
	);
}
